ALTER TABLE Tasks
ADD FOREIGN KEY (ID_P)
REFERENCES Projects(ID_P)
 
ALTER TABLE TaskTags
ADD FOREIGN KEY (ID_Tsk)
REFERENCES Tasks(ID_Tsk) 
 
ALTER TABLE TaskTags
ADD FOREIGN KEY (ID_Tag)
REFERENCES Tags(ID_Tag)
