ALTER TABLE Task
ADD FOREIGN KEY (project_ID)
REFERENCES Project(ID)
 
ALTER TABLE TaskTag
ADD FOREIGN KEY (task_ID)
REFERENCES Task(ID) 
 
ALTER TABLE TaskTag
ADD FOREIGN KEY (tag_ID)
REFERENCES Tag(ID)
